# Generated by Django 5.0.2 on 2024-02-22 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_a', models.IntegerField()),
                ('r_a', models.IntegerField()),
                ('k_a', models.IntegerField()),
                ('ab_a', models.IntegerField()),
                ('ac_a', models.IntegerField()),
                ('ad_a', models.IntegerField()),
                ('ae_a', models.IntegerField()),
                ('pop_b', models.IntegerField()),
                ('r_b', models.IntegerField()),
                ('k_b', models.IntegerField()),
                ('ab_b', models.IntegerField()),
                ('ac_b', models.IntegerField()),
                ('ad_b', models.IntegerField()),
                ('ae_b', models.IntegerField()),
                ('pop_c', models.IntegerField()),
                ('r_c', models.IntegerField()),
                ('k_c', models.IntegerField()),
                ('ab_c', models.IntegerField()),
                ('ac_c', models.IntegerField()),
                ('ad_c', models.IntegerField()),
                ('ae_c', models.IntegerField()),
                ('pop_d', models.IntegerField()),
                ('r_d', models.IntegerField()),
                ('k_d', models.IntegerField()),
                ('ab_d', models.IntegerField()),
                ('ac_d', models.IntegerField()),
                ('ad_d', models.IntegerField()),
                ('ae_d', models.IntegerField()),
                ('pop_e', models.IntegerField()),
                ('r_e', models.IntegerField()),
                ('k_e', models.IntegerField()),
                ('ab_e', models.IntegerField()),
                ('ac_e', models.IntegerField()),
                ('ad_e', models.IntegerField()),
                ('ae_e', models.IntegerField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
