# Generated by Django 5.0.2 on 2024-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
